from app import db
from app.models import Skill

# Define the skills with priorities
skills = [
    # Common skills
    {"name": "Rage dagger", "type": "Common", "priority": 1},
    {"name": "hard", "type": "Common", "priority": 2},
    {"name": "frostbite", "type": "Common", "priority": 3},
    {"name": "thunderbolt", "type": "Common", "priority": 4},
    {"name": "ghostly fuse", "type": "Common", "priority": 5},
    {"name": "killing freeze", "type": "Common", "priority": 6},
    {"name": "dodge", "type": "Common", "priority": 7},
    {"name": "critical frenzy", "type": "Common", "priority": 8},
    {"name": "healing dagger", "type": "Common", "priority": 9},
    {"name": "lightning dagger", "type": "Common", "priority": 10},
    {"name": "enhanced rage skill", "type": "Common", "priority": 11},
    {"name": "hits ice spike", "type": "Common", "priority": 12},
    {"name": "enhanced counterattack", "type": "Common", "priority": 13},
    {"name": "counter rate", "type": "Common", "priority": 14},
    {"name": "basic attack icy spikes", "type": "Common", "priority": 15},
    {"name": "enhanced basic attack", "type": "Common", "priority": 16},
    {"name": "heavy attack", "type": "Common", "priority": 17},
    {"name": "enhanced combo", "type": "Common", "priority": 18},
    {"name": "round-based lightning", "type": "Common", "priority": 19},
    {"name": "hits lightning", "type": "Common", "priority": 20},
    {"name": "dagger", "type": "Common", "priority": 21},
    {"name": "poison dagger", "type": "Common", "priority": 22},
    {"name": "rage icy spikes", "type": "Common", "priority": 23},
    {"name": "round light spear", "type": "Common", "priority": 24},
    {"name": "rage shield", "type": "Common", "priority": 25},
    {"name": "basic attack shield", "type": "Common", "priority": 26},
    {"name": "critical recovery", "type": "Common", "priority": 27},
    {"name": "basic attack sword chi", "type": "Common", "priority": 28},
    {"name": "round-based fire strike", "type": "Common", "priority": 29},
    {"name": "basic attack bolt", "type": "Common", "priority": 30},
    {"name": "poisoned weapon", "type": "Common", "priority": 31},
    {"name": "enhanced recovery enhance", "type": "Common", "priority": 32},
    {"name": "HP", "type": "Common", "priority": 33},
    {"name": "ATK", "type": "Common", "priority": 34},
    {"name": "DEF", "type": "Common", "priority": 35},
    {"name": "rage heal", "type": "Common", "priority": 36},
    {"name": "rage attack sword chi", "type": "Common", "priority": 37},
    {"name": "rage fire strike", "type": "Common", "priority": 38},
    {"name": "rage lightning", "type": "Common", "priority": 39},
    {"name": "hits recovery", "type": "Common", "priority": 40},
    {"name": "resilience", "type": "Common", "priority": 41},
    {"name": "fire guard", "type": "Common", "priority": 42},
    {"name": "lifesteal", "type": "Common", "priority": 43},
    {"name": "battle cry", "type": "Common", "priority": 44},
    {"name": "starting light spear", "type": "Common", "priority": 45},
    {"name": "rage light spear", "type": "Common", "priority": 46},
    {"name": "flames from above", "type": "Common", "priority": 47},
    {"name": "lightning from above", "type": "Common", "priority": 48},
    {"name": "swift revenge", "type": "Common", "priority": 49},

    # Legendary skills
    {"name": "Crit Mastery", "type": "Legendary", "priority": 1},
    {"name": "Frozen Touch", "type": "Legendary", "priority": 2},
    {"name": "Dagger Mastery", "type": "Legendary", "priority": 3},
    {"name": "dagger cooldown", "type": "Legendary", "priority": 4},
    {"name": "counter mastery", "type": "Legendary", "priority": 5},
    {"name": "alchemist", "type": "Legendary", "priority": 6},
    {"name": "shrink spell", "type": "Legendary", "priority": 7},
    {"name": "royal crown", "type": "Legendary", "priority": 8},
    {"name": "shock discharge", "type": "Legendary", "priority": 9},
    {"name": "combo mastery", "type": "Legendary", "priority": 10},
    {"name": "critical shield", "type": "Legendary", "priority": 11},
    {"name": "dagger proficiency", "type": "Legendary", "priority": 12},
    {"name": "rage mastery", "type": "Legendary", "priority": 13},
    {"name": "multiple lightning", "type": "Legendary", "priority": 14},
    {"name": "rage proficiency", "type": "Legendary", "priority": 15},
    {"name": "spell master", "type": "Legendary", "priority": 16},
    {"name": "smelly dagger", "type": "Legendary", "priority": 17},
    {"name": "burning proficiency", "type": "Legendary", "priority": 18},
    {"name": "triple blasts", "type": "Legendary", "priority": 19},
    {"name": "magic flames", "type": "Legendary", "priority": 20},
    {"name": "lightning mastery", "type": "Legendary", "priority": 21},
    {"name": "thunderstorm", "type": "Legendary", "priority": 22},
    {"name": "berserker", "type": "Legendary", "priority": 23},
    {"name": "tyrant", "type": "Legendary", "priority": 24},
    {"name": "Huge HP", "type": "Legendary", "priority": 25},
    {"name": "Huge ATK", "type": "Legendary", "priority": 26},
    {"name": "Huge DEF", "type": "Legendary", "priority": 27},
    {"name": "Critical Dodge", "type": "Legendary", "priority": 28},
    {"name": "Multi Strike", "type": "Legendary", "priority": 29},
    {"name": "Recovery Sword Chi", "type": "Legendary", "priority": 30},
    {"name": "Dual Hits", "type": "Legendary", "priority": 31},

    # Mythic skills
    {"name": "War Veteran", "type": "Mythic", "priority": 1},
    {"name": "Battle-Hardened", "type": "Mythic", "priority": 2},
    {"name": "Super Life", "type": "Mythic", "priority": 3},
    {"name": "Golden Egg", "type": "Mythic", "priority": 4},
    {"name": "Trinity Force", "type": "Mythic", "priority": 5},
    {"name": "Combo Dagger", "type": "Mythic", "priority": 6},
    {"name": "Deadly Spikes", "type": "Mythic", "priority": 7},
    {"name": "Super ATK", "type": "Mythic", "priority": 8},
    {"name": "Super DEF", "type": "Mythic", "priority": 9},
    {"name": "Magic Spear", "type": "Mythic", "priority": 10},
    {"name": "Super Lightning", "type": "Mythic", "priority": 11},
    {"name": "Pyromancer", "type": "Mythic", "priority": 12},
    {"name": "Counter Soul", "type": "Mythic", "priority": 13},
    {"name": "Indestructible", "type": "Mythic", "priority": 14},
    {"name": "Combo Spirit", "type": "Mythic", "priority": 15},
    {"name": "Rage Combo", "type": "Mythic", "priority": 16},
    {"name": "Werewolf!", "type": "Mythic", "priority": 17},
    {"name": "Wizard!", "type": "Mythic", "priority": 18},
    {"name": "Orc!", "type": "Mythic", "priority": 19},
    {"name": "Firecracker", "type": "Mythic", "priority": 20},
    {"name": "Heat Explosion", "type": "Mythic", "priority": 21},
    {"name": "Glass Cannon", "type": "Mythic", "priority": 22},
    {"name": "Vampire", "type": "Mythic", "priority": 23},
    {"name": "Revive", "type": "Mythic", "priority": 24},
    {"name": "Super Sword Chi", "type": "Mythic", "priority": 25},
    {"name": "Tamer!", "type": "Mythic", "priority": 26},

]

# Add skills to the database
for skill in skills:
    db.session.add(Skill(name=skill["name"], type=skill["type"], priority=skill["priority"]))

# Commit the changes
db.session.commit()

print("Skills added successfully!")
